name: release

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: install moonbit
        run: |
          curl -fsSL https://cli.moonbitlang.com/install/unix.sh | bash
          echo "$HOME/.moon/bin" >> $GITHUB_PATH

      - name: moon check
        run: moon update && moon version && moon check --target js

      - name: moon test
        run: moon build --target js --debug

      - name: setup credentials
        run: |
          mkdir -p ~/.moon
          echo '${{ secrets.MOON_CREDENTIALS }}' > ~/.moon/credentials.json

      - name: moon publish
        run: moon publish
